package bizgen

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// 生成 RPC 包装代码。
func generateRPC(res *scanResult, module string) error {
	rpcDir := filepath.Join(res.RootDir, "internal", module, "interfaces", "rpc")
	if err := os.MkdirAll(rpcDir, 0o755); err != nil {
		return err
	}
	path := filepath.Join(rpcDir, "zz_rpc_gen.go")
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()

	eps := res.Endpoints
	if len(eps) == 0 {
		return nil
	}

	endpointType := "Endpoint"
	if eps[0].StructName != "" {
		endpointType = eps[0].StructName
	}

	fmt.Fprintln(f, "// Code generated by bizgen; DO NOT EDIT.")
	fmt.Fprintln(f, "package rpc")
	fmt.Fprintln(f)
	fmt.Fprintln(f, "import (")
	fmt.Fprintln(f, "\t\"encoding/json\"")
	fmt.Fprintf(f, "\t\"%s/internal/%s/interfaces/endpoint\"\n", res.ModPath, module)
	fmt.Fprintf(f, "\t\"%s/pkg/biz\"\n", res.ModPath)
	fmt.Fprintf(f, "\t\"%s/pkg/errs\"\n", res.ModPath)
	fmt.Fprintf(f, "\t\"%s/pkg/validate\"\n", res.ModPath)
	fmt.Fprintln(f, ")")
	fmt.Fprintln(f)
	fmt.Fprintln(f, "// RegisterRPC is generated from endpoint annotations.")
	fmt.Fprintf(f, "func RegisterRPC(r biz.RPCRouter, ep *endpoint.%s) {\n", endpointType)

	for _, e := range eps {
		if e.RPCMethod == "" {
			continue
		}
		bizTag := strings.ToLower(module + "." + strings.ToLower(e.MethodName))

		fmt.Fprintf(f, "\tr.Handle(%q, func(ctx biz.Context, raw json.RawMessage) (any, error) {\n", e.RPCMethod)
		fmt.Fprintf(f, "\t\tvar req endpoint.%sReq\n", e.MethodName)
		fmt.Fprintln(f, "\t\tif err := json.Unmarshal(raw, &req); err != nil {")
		fmt.Fprintln(f, "\t\t\treturn nil, errs.BadRequest(\"invalid params\").WithCause(err)")
		fmt.Fprintln(f, "\t\t}")
		fmt.Fprintln(f, "\t\tif err := validate.Struct(&req); err != nil {")
		fmt.Fprintln(f, "\t\t\treturn nil, err")
		fmt.Fprintln(f, "\t\t}")
		fmt.Fprintf(f, "\t\treturn ep.%s(ctx, &req)\n", e.MethodName)
		fmt.Fprintf(f, "\t}, biz.WithBizTag(%q))\n", bizTag)
	}

	fmt.Fprintln(f, "}")
	return nil
}
