package user

import (
    "github.com/youbuwei/doeot-go/internal/user/app"
    "github.com/youbuwei/doeot-go/internal/user/infra/repo"
    "github.com/youbuwei/doeot-go/internal/user/interfaces/endpoint"
    userhttp "github.com/youbuwei/doeot-go/internal/user/interfaces/http"
    userrpc "github.com/youbuwei/doeot-go/internal/user/interfaces/rpc"
    "github.com/youbuwei/doeot-go/pkg/biz"
    "gorm.io/gorm"
)

// Module is the user business module, implementing biz.Module.
type Module struct {
    ep *endpoint.UserEndpoint
}

// NewModule wires dependencies into the endpoint graph.
// In a real project this wiring can be generated by a DI tool like google/wire.
func NewModule(db *gorm.DB) *Module {
    r := repo.NewRepo(db)
    svc := app.NewUserService(r)
    ep := &endpoint.UserEndpoint{Svc: svc}
    return &Module{ep: ep}
}

func (m *Module) Name() string { return "user" }

// RegisterHTTP hooks HTTP routes.
func (m *Module) RegisterHTTP(r biz.Router) {
    userhttp.RegisterRoutes(r, m.ep)
}

// RegisterRPC hooks RPC methods.
func (m *Module) RegisterRPC(r biz.RPCRouter) {
    userrpc.RegisterRPC(r, m.ep)
}
